platform :ios, '6.0' 
pod 'SHTextFieldBlocks', :path => '../'
pod 'SHSegueBlocks'

target :ExampleTests do
  pod 'SHTestCaseAdditions'        #, :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod 'SHFastEnumerationProtocols' #, :git => "https://github.com/PodFactory/SHFastEnumerationProtocols"
  pod "KIF-next"
end